# FriendlyChat Codelab

use_frameworks!
platform :ios, '9.0'

pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Fabric'
pod 'Crashlytics'
pod 'GoogleSignIn'

target 'FriendlyChatSwift' do
end
