# FriendlyChat Codelab

use_frameworks!
platform :ios, '9.0'

pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Invites'
pod 'Firebase/Messaging'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'
pod 'Fabric', '~> 1.7.2'
pod 'Crashlytics', '~> 3.9.3'

target 'FriendlyChatSwift' do
end
