# FriendlyChat Codelab

platform :ios, '8.0'

pod 'GoogleSignIn'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Crashlytics'
pod 'Firebase/Database'
pod 'Firebase/InAppMessagingDisplay'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'

target 'FriendlyChatObjC' do
end
