# FriendlyChat Codelab

use_frameworks!
platform :ios, '8.0'

pod 'GoogleSignIn'
pod 'Firebase/Core'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Crashlytics'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/InAppMessagingDisplay'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Storage'

target 'FriendlyChatSwift' do
end
